# Generated by Django 2.1.10 on 2019-08-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0021_auto_20010101_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone_number',
            field=models.IntegerField(max_length=100),
        ),
    ]
