# Generated by Django 2.1.10 on 2019-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0022_auto_20190810_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
