# Generated by Django 2.1.10 on 2019-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0021_auto_20190723_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='l_1_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_10',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_5',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_6',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_7',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_8',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_9',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_10',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_5',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_6',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_7',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_8',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_9',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
