# Generated by Django 2.1.10 on 2019-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0026_auto_20190821_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='l_1_10_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_1_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_2_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_3_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_4_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_5_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_6_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_7_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_8_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_1_9_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_10_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_1_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_2_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_3_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_4_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_5_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_6_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_7_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_8_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='l_2_9_body',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
