# Generated by Django 2.1.10 on 2019-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0027_auto_20190827_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub1_child1_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child1_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child2_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child2_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child3_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child3_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child4_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child4_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child5_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub1_child5_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child1_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child1_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child2_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child2_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child3_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child3_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child4_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child4_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child5_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub2_child5_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child1_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child1_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child2_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child2_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child3_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child3_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child4_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child4_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child5_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub3_child5_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child1_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child1_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child2_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child2_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child3_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child3_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child4_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child4_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child5_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub4_child5_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child1_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child1_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child2_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child2_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child3_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child3_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child4_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child4_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child5_body2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='sub5_child5_body3',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
